import { Test } from './types';

export const TESTS: Test[] = [
  {
    id: 'test-001',
    title: '你是哪种抽象人格？',
    emoji: '🐾',
    badge: 'HOT',
    description: '在这个充满熵增的世界里，你的灵魂究竟呈现出怎样的几何形态？是圆润的妥协，还是尖锐的叛逆？',
    questionCount: 5,
    participantCount: 12453,
    questions: [
      {
        id: 'q1',
        text: '当你看到一只薛定谔的猫，你的第一反应是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '它一定还活着，因为我爱它', value: 10 },
          { id: 'o2', text: '它是死是活与我何干，我是狗派', value: 50 },
          { id: 'o3', text: '我会打开盒子，直面混沌', value: 30 },
          { id: 'o4', text: '我不存在，猫也不存在', value: 80 },
        ],
      },
      {
        id: 'q2',
        text: '深夜三点，你的大脑在播放什么？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '明天要交的OKR', value: 10 },
          { id: 'o2', text: '前任的模糊背影', value: 30 },
          { id: 'o3', text: '宇宙爆炸的默片', value: 80 },
          { id: 'o4', text: '纯粹的白噪音', value: 50 },
        ],
      },
      {
        id: 'q3',
        text: '如果必须变成一种无机物，你选择：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '路边的鹅卵石', value: 40 },
          { id: 'o2', text: '被遗忘的塑料袋', value: 70 },
          { id: 'o3', text: '博物馆的钻石', value: 20 },
          { id: 'o4', text: '下水道的井盖', value: 60 },
        ],
      },
      {
        id: 'q4',
        text: '面对无法解决的Bug（或人生难题），你会：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '暴力重构', value: 30 },
          { id: 'o2', text: '假装没看见，继续运行', value: 60 },
          { id: 'o3', text: '删库跑路', value: 90 },
          { id: 'o4', text: '祈祷神明（或CTO）', value: 20 },
        ],
      },
      {
        id: 'q5',
        text: '你认为“自由”的味道是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '焦糖玛奇朵', value: 20 },
          { id: 'o2', text: '雨后的泥土', value: 40 },
          { id: 'o3', text: '消毒水味', value: 80 },
          { id: 'o4', text: '没有任何味道', value: 60 },
        ],
      },
    ],
    results: [
      {
        id: 'r1',
        name: '秩序守护者',
        emoji: '📐',
        minScore: 0,
        maxScore: 120,
        description: '你的灵魂方方正正，容不下一丝混沌。你是熵减的英雄。',
        insights: ['极其守时', '强迫症晚期', '不仅整理房间，还整理心情'],
        recommendations: ['试着在周五晚上关掉手机', '允许自己犯一个愚蠢的错误', '喝一杯不加糖的咖啡'],
      },
      {
        id: 'r2',
        name: '虚无主义猫',
        emoji: '🐱',
        minScore: 121,
        maxScore: 220,
        description: '如果灵魂有形状，你是一只流体猫。你适应一切，也拒绝一切。',
        insights: ['间歇性踌躇满志', '持续性混吃等死', '内心戏丰富但表情瘫痪'],
        recommendations: ['去晒晒太阳，别思考意义', '吃一顿好的', '养一只真的猫'],
      },
      {
        id: 'r3',
        name: '赛博精神病',
        emoji: '🧬',
        minScore: 221,
        maxScore: 400,
        description: '你的思维跳跃如量子纠缠，普通人无法捕捉你的频率。',
        insights: ['常被人说脑回路清奇', '其实你是外星人卧底', '在此刻与彼刻之间反复横跳'],
        recommendations: ['写小说，或者写代码', '不要试图向人类解释自己', '保持疯狂'],
      },
    ],
  },
  {
    id: 'test-002',
    title: '你的情绪垃圾桶容量有多大？',
    emoji: '🗑️',
    badge: 'NEW',
    description: '每天都在接收负能量，你的内心存储空间告急了吗？测测你需要多少个T的硬盘。',
    questionCount: 4,
    participantCount: 8902,
    questions: [
      {
        id: 'q1',
        text: '当同事把锅甩给你时，你内心的OS是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '行吧，我来carry', value: 10 },
          { id: 'o2', text: '微笑，然后在心里扎小人', value: 30 },
          { id: 'o3', text: '直接开怼', value: 50 },
          { id: 'o4', text: '已经习惯了，麻木', value: 70 },
        ],
      },
      {
        id: 'q2',
        text: '周末只想做什么？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '特种兵式旅游', value: 10 },
          { id: 'o2', text: '躺平，外卖，刷剧', value: 40 },
          { id: 'o3', text: '大扫除', value: 20 },
          { id: 'o4', text: '关机失联', value: 60 },
        ],
      },
      {
        id: 'q3',
        text: '朋友向你抱怨恋人，你会：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '理性分析，劝分劝和', value: 10 },
          { id: 'o2', text: '一起骂，输出情绪', value: 30 },
          { id: 'o3', text: '左耳进右耳出', value: 50 },
          { id: 'o4', text: '打断施法，借钱免谈', value: 70 },
        ],
      },
      {
        id: 'q4',
        text: '看到感人的电影，你会哭吗？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '哭得稀里哗啦', value: 10 },
          { id: 'o2', text: '眼眶湿润', value: 20 },
          { id: 'o3', text: '内心毫无波澜', value: 60 },
          { id: 'o4', text: '尴尬得脚趾扣地', value: 40 },
        ],
      }
    ],
    results: [
      {
        id: 'r1',
        name: '钛合金垃圾桶',
        emoji: '🛡️',
        minScore: 0,
        maxScore: 100,
        description: '你不仅能装，还能自动降解。你是朋友们最坚实的依靠，但别忘了倒垃圾。',
        insights: ['共情能力极强', '容易成为情绪垃圾站', '治愈系天使'],
        recommendations: ['学会说“不”', '定期清理内心缓存', '给自己买束花'],
      },
      {
        id: 'r2',
        name: '一次性纸杯',
        emoji: '🥤',
        minScore: 101,
        maxScore: 300,
        description: '你的容量很小，一碰就洒。这不怪你，是世界太糟糕了。',
        insights: ['敏感易碎', '防御机制很强', '容易炸毛'],
        recommendations: ['远离有毒的人际关系', '多做深呼吸', '允许自己脆弱'],
      },
    ],
  },
  {
    id: 'test-003',
    title: '你的灵魂形状是什么？',
    emoji: '✨',
    badge: 'LIMITED',
    description: '如果把你的灵魂放入三维建模软件，它会是一个怎么样的拓扑结构？',
    questionCount: 3,
    participantCount: 5600,
    questions: [
      {
        id: 'q1',
        text: '选一个几何体代表你：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '球体', value: 10 },
          { id: 'o2', text: '正四面体', value: 30 },
          { id: 'o3', text: '莫比乌斯环', value: 60 },
          { id: 'o4', text: '克莱因瓶', value: 90 },
        ],
      },
      {
        id: 'q2',
        text: '你更喜欢哪种美学？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '极简主义', value: 20 },
          { id: 'o2', text: '蒸汽朋克', value: 40 },
          { id: 'o3', text: '赛博朋克', value: 60 },
          { id: 'o4', text: '故障艺术', value: 80 },
        ],
      },
      {
        id: 'q3',
        text: '人生的尽头是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '回归尘土', value: 20 },
          { id: 'o2', text: '数字飞升', value: 80 },
          { id: 'o3', text: '无尽轮回', value: 50 },
          { id: 'o4', text: '没想过', value: 10 },
        ],
      }
    ],
    results: [
      {
        id: 'r1',
        name: '正多面体',
        emoji: '🧊',
        minScore: 0,
        maxScore: 100,
        description: '稳定、坚固、有原则。你是混乱世界中的定海神针。',
        insights: ['原则性强', '不易被改变', '值得信赖'],
        recommendations: ['偶尔圆滑一点也没关系', '尝试一些不确定的事'],
      },
      {
        id: 'r2',
        name: '高维碎片',
        emoji: '💠',
        minScore: 101,
        maxScore: 300,
        description: '你属于四维空间，三维世界只是你的投影。没人能真正看透你。',
        insights: ['思维深邃', '常有惊人之语', '孤独的观察者'],
        recommendations: ['寻找你的同类', '记录你的梦境'],
      },
    ],
  },
];
