import { Test } from './types';

export const TESTS: Test[] = [
  {
    id: 'test-001',
    title: '你的抽象人格成分表',
    emoji: '🐾',
    badge: 'HOT',
    description: '在被算法和规训包裹的日常里，你的潜意识究竟呈现出怎样的混沌形态？是通过伪装存活的拟态生物，还是拒绝被定义的故障乱码？',
    questionCount: 9,
    participantCount: 42109,
    questions: [
      {
        id: 'q1',
        text: '如果你在一间没有门的纯白房间醒来，墙上有一扇窗户展示着你从未见过的颜色，你的第一反应是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '感到恐慌，疯狂寻找隐藏的出口逻辑', value: 10 },
          { id: 'o2', text: '试图用已知的语言去定义那种颜色', value: 30 },
          { id: 'o3', text: '意识到这可能是一场清醒梦，开始从容探索', value: 60 },
          { id: 'o4', text: '极度兴奋，甚至想尝尝那种颜色是什么味道', value: 90 },
        ],
      },
      {
        id: 'q2',
        text: '深夜三点，大脑强制开机，此时你脑海中自动播放的画面是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '高清循环播放五年前犯下的某个尴尬错误', value: 20 },
          { id: 'o2', text: '关于未来生活的一百种灾难性预演', value: 10 },
          { id: 'o3', text: '一部逻辑严密但毫无意义的原创科幻电影', value: 60 },
          { id: 'o4', text: '无法名状的几何图形和刺耳的白噪音', value: 90 },
        ],
      },
      {
        id: 'q3',
        text: '如果必须将你的社交状态具象化为一个物体，你会选择：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '一台长期处于“飞行模式”的手机', value: 40 },
          { id: 'o2', text: '一面能够完美反射他人期待的镜子', value: 20 },
          { id: 'o3', text: '一个仅供参观但禁止触摸的玻璃展柜', value: 60 },
          { id: 'o4', text: '一团不断变形、由于过热而冒烟的线路板', value: 80 },
        ],
      },
      {
        id: 'q4',
        text: '走在路上看到一棵树的贴图穿模了（悬浮在空中），你会：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '揉揉眼睛，怀疑自己最近太累了', value: 10 },
          { id: 'o2', text: '立刻拍照发朋友圈：“这世界果然是个草台班子”', value: 40 },
          { id: 'o3', text: '习以为常，毕竟现实本身就是充满漏洞的', value: 70 },
          { id: 'o4', text: '试图爬上去，看看能不能卡进地图的背面', value: 90 },
        ],
      },
      {
        id: 'q5',
        text: '在便利店买水时，你突然觉得收银员看你的眼神很奇怪，你会想：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '我脸上沾东西了吗？（立刻照镜子）', value: 20 },
          { id: 'o2', text: '他可能只是在发呆，与我无关', value: 40 },
          { id: 'o3', text: '他是不是看穿了我是个外星间谍？', value: 80 },
          { id: 'o4', text: '立刻用更奇怪的眼神瞪回去，建立威慑', value: 60 },
        ],
      },
      {
        id: 'q6',
        text: '如果你的生命只剩下最后10分钟，你会用来做什么？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '给最爱的人打电话，认真告别', value: 10 },
          { id: 'o2', text: '删光浏览记录，格式化硬盘', value: 30 },
          { id: 'o3', text: '躺下来，安静地数自己的心跳', value: 50 },
          { id: 'o4', text: '试图在这10分钟内悟出宇宙的终极真理', value: 90 },
        ],
      },
      {
        id: 'q7',
        text: '你认为“自由”的气味闻起来像：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '昂贵香水与新钞票的混合味', value: 10 },
          { id: 'o2', text: '暴雨冲刷过后带着腥气的泥土味', value: 50 },
          { id: 'o3', text: '外太空的真空味（如果是那种味道的话）', value: 80 },
          { id: 'o4', text: '没有任何气味，是一种绝对的虚无', value: 60 },
        ],
      },
      {
        id: 'q8',
        text: '面对无法解决的人生Bug（比如毫无意义的工作），你的应对策略是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '暴力重构：试图推翻一切重来，哪怕代价巨大', value: 70 },
          { id: 'o2', text: '兼容运行：假装没看见报错，继续维持系统运转', value: 10 },
          { id: 'o3', text: '断网下线：在物理或精神上彻底消失', value: 50 },
          { id: 'o4', text: '召唤神明：转发锦鲤、塔罗占卜或向宇宙下订单', value: 30 },
        ],
      },
      {
        id: 'q9',
        text: '你最希望拥有的超能力是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '读心术，掌控所有社交局面', value: 20 },
          { id: 'o2', text: '隐身术，想消失就消失', value: 50 },
          { id: 'o3', text: '时间暂停，让我多睡一会儿', value: 40 },
          { id: 'o4', text: '把任何物体变成猫', value: 90 },
        ],
      },
    ],
    results: [
      {
        id: 'r1',
        name: '混凝土锚点',
        emoji: '🏗️',
        minScore: 0,
        maxScore: 200,
        description: '你是混乱现实中最后的防线。你的灵魂由钢筋和逻辑浇筑而成，在这个熵增的世界里，你不仅能维持自身的秩序，还能成为他人的引力中心。虽然有时被评价为“无趣”，但只有你知道，清醒是最大的疯狂。',
        insights: ['逻辑闭环掌控者', '现实主义晚期', '不仅整理房间，还整理命运'],
        recommendations: ['允许自己在周五晚上短暂地崩塌', '尝试做一件完全没有意义的事', '去淋一场雨，别打伞'],
      },
      {
        id: 'r2',
        name: '清醒梦旅人',
        emoji: '🎐',
        minScore: 201,
        maxScore: 400,
        description: '你行走在现实与幻想的边缘，拥有随时抽离的能力。你既能熟练扮演社会赋予的角色，又在内心保留了一座无人知晓的空中花园。你是一只适应力极强的变色龙，也是一位从未真正睡着的观察者。',
        insights: ['间歇性踌躇满志', '持续性精神漫游', '内心戏足以拍三季美剧'],
        recommendations: ['将梦境记录下来，它们是潜意识的情书', '寻找一个能听懂你胡言乱语的同类', '别在扮演中迷失了本体'],
      },
      {
        id: 'r3',
        name: '故障漫游者',
        emoji: '👾',
        minScore: 401,
        maxScore: 600,
        description: '你已经看透了世界的源代码，并发现到处都是Bug。你对主流价值观保持着一种戏谑的疏离感，像是一个误入地球的高维生物。你不再试图修复错误，而是学会了在故障中跳舞，享受这种荒诞的虚无感。',
        insights: ['赛博虚无主义', '由于看太透而显得冷漠', '总是能发现盲点'],
        recommendations: ['去创作吧，哪怕是乱码也是艺术', '不要试图向NPC解释你的世界观', '保持这种迷人的锋利'],
      },
      {
        id: 'r4',
        name: '熵增实体',
        emoji: '🌀',
        minScore: 601,
        maxScore: 900,
        description: '你的存在本身就是对秩序的挑战。你的思维如同量子纠缠般不可预测，充满了创造性的毁灭力量。你不需要被理解，因为“理解”本身就是一种降维打击。你是风暴，是混沌，是无限的可能性。',
        insights: ['混乱中立', '行走的黑天鹅事件', 'san值常年波动'],
        recommendations: ['小心不要误伤凡人', '寻找能承载你能量的容器', '继续燃烧，直到宇宙热寂'],
      },
    ],
  },
  {
    id: 'test-002',
    title: '你的精神内耗程度是多少？',
    emoji: '🗑️',
    badge: 'NEW',
    description: '每天都在与自己博弈，你的内心CPU是否已经过载？测测你是自动净化的处理器，还是不断堆积缓存的旧硬盘。',
    questionCount: 8,
    participantCount: 28902,
    questions: [
      {
        id: 'q1',
        text: '当朋友在聊天中突然回复变得冷淡（比如发了“哦”），你会：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '毫不在意，可能TA在忙', value: 10 },
          { id: 'o2', text: '稍微想一下，然后去做别的事', value: 30 },
          { id: 'o3', text: '翻看聊天记录，反思自己是否说错了话', value: 70 },
          { id: 'o4', text: '陷入焦虑，脑补出一段友情破裂的剧本', value: 90 },
        ],
      },
      {
        id: 'q2',
        text: '周末本打算早起学习/工作，结果睡到了下午两点，你会觉得：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '爽！这才是周末！', value: 0 },
          { id: 'o2', text: '有点可惜，晚上补回来吧', value: 20 },
          { id: 'o3', text: '充满罪恶感，一边玩手机一边责怪自己', value: 60 },
          { id: 'o4', text: '这一天废了，我真是个废物', value: 90 },
        ],
      },
      {
        id: 'q3',
        text: '发了一条朋友圈/动态，过了10分钟还没有人点赞，你会：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '无所谓，本来就是发给自己看的', value: 10 },
          { id: 'o2', text: '有点失落，但懒得管', value: 30 },
          { id: 'o3', text: '怀疑自己是不是被限流了，或者文案有问题', value: 60 },
          { id: 'o4', text: '感到羞耻，立刻删除', value: 90 },
        ],
      },
      {
        id: 'q4',
        text: '如果在公开场合说错了话，这个记忆会困扰你多久？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '5分钟，大家都很忙没人在意的', value: 10 },
          { id: 'o2', text: '一天，睡一觉就好了', value: 30 },
          { id: 'o3', text: '一个月，偶尔想起来还是会脚趾扣地', value: 60 },
          { id: 'o4', text: '一辈子，这不仅是尴尬，这是人生污点', value: 90 },
        ],
      },
      {
        id: 'q5',
        text: '如果你的情绪有一个具象化的容器，它长什么样？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '一个底部有漏洞的筛子（留不住坏情绪）', value: 10 },
          { id: 'o2', text: '定期清空的回收站', value: 30 },
          { id: 'o3', text: '深不见底的黑洞', value: 80 },
          { id: 'o4', text: '随时可能爆炸的高压锅', value: 60 },
        ],
      },
      {
        id: 'q6',
        text: '面对他人的负面情绪倾诉，你的真实感受是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '冷静分析，提供解决方案', value: 20 },
          { id: 'o2', text: '感同身受，跟着一起难过', value: 50 },
          { id: 'o3', text: '表面在听，内心在想怎么逃离', value: 40 },
          { id: 'o4', text: '像被吸干了精力，甚至产生生理性不适', value: 80 },
        ],
      },
      {
        id: 'q7',
        text: '做决定对你来说是一件困难的事吗？（比如点外卖）',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '不困难，想要什么很明确', value: 10 },
          { id: 'o2', text: '一般，看看推荐就选了', value: 30 },
          { id: 'o3', text: '困难，会在两个选项间反复横跳', value: 60 },
          { id: 'o4', text: '灾难，选错了会后悔一整天', value: 90 },
        ],
      },
      {
        id: 'q8',
        text: '你是否经常在脑海里和“想象中的人”吵架（或者重演过去的争吵）？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '从不，过去了就是过去了', value: 0 },
          { id: 'o2', text: '偶尔，为了下次能发挥好点', value: 30 },
          { id: 'o3', text: '经常，洗澡时是高发期', value: 60 },
          { id: 'o4', text: '每天，我内心住着一个辩论队', value: 90 },
        ],
      }
    ],
    results: [
      {
        id: 'r1',
        name: '特氟龙不粘锅',
        emoji: '🍳',
        minScore: 0,
        maxScore: 160,
        description: '你拥有令人羡慕的“钝感力”。坏情绪在你身上就像水珠落在荷叶上，滑过不留痕。这并不是冷漠，而是你拥有极其健康的心理边界。你知道如何保护自己的能量，是反内耗的高手。',
        insights: ['拒绝精神反刍', '睡一觉就好', '人间清醒'],
        recommendations: ['继续保持这种松弛感', '把你的秘诀教给身边的人', '注意不要显得太没人情味'],
      },
      {
        id: 'r2',
        name: '智能回收站',
        emoji: '♻️',
        minScore: 161,
        maxScore: 350,
        description: '你是一个运转良好的情绪处理器。虽然会有负面情绪，但你建立了一套自我消化的机制。你懂得适时地按下“清空”键，在敏感与钝感之间找到了完美的平衡点。',
        insights: ['情绪管理大师', '能屈能伸', '虽然会emo但好得快'],
        recommendations: ['给自己安排定期的“情绪排毒日”', '多接触大自然', '不要承担不属于你的责任'],
      },
      {
        id: 'r3',
        name: '高敏易碎品',
        emoji: '🥃',
        minScore: 351,
        maxScore: 500,
        description: '你的雷达太灵敏了，能捕捉到空气中微弱的情绪波动。这赋予了你极强的共情能力和艺术感知力，但也让你容易被外界的噪音所伤。你的内心像精致的玻璃，美丽却需要小心轻放。',
        insights: ['高敏感人格(HSP)', '想太多是本能', '容易把别人的错归结于自己'],
        recommendations: ['学会对他人说“不”', '练习冥想，把注意力拉回当下', '接受自己的敏感，那是天赋'],
      },
      {
        id: 'r4',
        name: '放射性核心',
        emoji: '☢️',
        minScore: 501,
        maxScore: 720,
        description: '你的内部正在发生剧烈的核反应。过度的自我反省和对他人的过度在意，让你的精神时刻处于高压状态。你不仅自己在内耗，这种焦灼的能量场甚至可能灼伤接近你的人。你需要紧急降温。',
        insights: ['内耗晚期', '自我攻击', '看似平静，实则崩塌'],
        recommendations: ['停止追求完美', '尝试“粗糙”地生活', '必要时寻求专业心理咨询'],
      },
    ],
  },
  {
    id: 'test-003',
    title: '你的灵魂拓扑结构',
    emoji: '💠',
    badge: 'LIMITED',
    description: '如果把你放入高维空间进行建模，你的灵魂会呈现出怎样的几何形态？是坚不可摧的立方体，还是没有尽头的莫比乌斯环？',
    questionCount: 8,
    participantCount: 15600,
    questions: [
      {
        id: 'q1',
        text: '你对“时间”的感知更接近于：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '一条笔直向前的射线，不可逆转', value: 10 },
          { id: 'o2', text: '一个不断重复的圆环，历史总是惊人相似', value: 40 },
          { id: 'o3', text: '向外扩散的螺旋，虽然重复但在上升', value: 60 },
          { id: 'o4', text: '一团混乱的毛线球，过去、现在和未来同时存在', value: 90 },
        ],
      },
      {
        id: 'q2',
        text: '做重大决定时，你的决策模型是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '列出Excel表格，计算利弊权重', value: 10 },
          { id: 'o2', text: '凭直觉，相信第一反应', value: 50 },
          { id: 'o3', text: '抛硬币，或者看塔罗牌怎么说', value: 70 },
          { id: 'o4', text: '等待“神启”般的灵光一闪', value: 80 },
        ],
      },
      {
        id: 'q3',
        text: '如果让你选择一个精神栖息地，你会选：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '极简主义的纯白包豪斯建筑', value: 10 },
          { id: 'o2', text: '充满古书和灰尘的维多利亚式图书馆', value: 40 },
          { id: 'o3', text: '终年下雨、霓虹闪烁的赛博朋克街道', value: 70 },
          { id: 'o4', text: '长满发光蘑菇的迷幻森林', value: 60 },
        ],
      },
      {
        id: 'q4',
        text: '你最喜欢的数学概念是：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '勾股定理（经典，完美，永恒）', value: 10 },
          { id: 'o2', text: '虚数i（不存在但必须存在）', value: 60 },
          { id: 'o3', text: '无限不循环小数π（混乱中的秩序）', value: 40 },
          { id: 'o4', text: '薛定谔的猫（既死又活的叠加态）', value: 90 },
        ],
      },
      {
        id: 'q5',
        text: '如果你能看到世界的“底层代码”，你觉得它会是什么？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '整齐排列的0和1', value: 20 },
          { id: 'o2', text: '像乐谱一样流动的音符', value: 40 },
          { id: 'o3', text: '一堆纠缠在一起的彩色琴弦', value: 60 },
          { id: 'o4', text: '一片纯粹的、震耳欲聋的白光', value: 90 },
        ],
      },
      {
        id: 'q6',
        text: '你如何定义“自我”？',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '我是我的肉体加上社会身份的总和', value: 10 },
          { id: 'o2', text: '我是一段连续的记忆流', value: 40 },
          { id: 'o3', text: '我是宇宙体验自身的一个触角', value: 70 },
          { id: 'o4', text: '我是一个系统错误，或者是缸中之脑', value: 90 },
        ],
      },
      {
        id: 'q7',
        text: '当面对一个无法解开的死结（Paradox）时，你会：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '拿剪刀把它剪断', value: 10 },
          { id: 'o2', text: '一点点耐心解开', value: 30 },
          { id: 'o3', text: '把它当作一个艺术品欣赏', value: 60 },
          { id: 'o4', text: '认为这也是结的一种形态，没必要解开', value: 80 },
        ],
      },
      {
        id: 'q8',
        text: '如果可以抛弃肉体，将意识上传云端获得永生，你会：',
        type: 'single-choice',
        options: [
          { id: 'o1', text: '绝对不要，没有感官就没有活着', value: 0 },
          { id: 'o2', text: '犹豫，担心被大公司控制', value: 30 },
          { id: 'o3', text: '愿意，肉体只是沉重的皮囊', value: 80 },
          { id: 'o4', text: '我已经上传了，现在和你对话的就是数据', value: 100 },
        ],
      }
    ],
    results: [
      {
        id: 'r1',
        name: '正六面体',
        emoji: '🧊',
        minScore: 0,
        maxScore: 180,
        description: '你的灵魂结构是最稳定的柏拉图多面体。你讲究原则，信奉秩序，是混乱世界中的基石。你的内心有着清晰的坐标系，无论外界如何旋转，你始终知道自己的方位。坚固，可靠，但也可能稍显棱角分明。',
        insights: ['原则性强', '抗压能力Max', '有时候过于固执'],
        recommendations: ['偶尔打磨一下棱角', '试着接受一些不确定性', '去拥抱柔软的事物'],
      },
      {
        id: 'r2',
        name: '彭罗斯三角',
        emoji: '🔺',
        minScore: 181,
        maxScore: 360,
        description: '你是一个不可能图形。乍看之下逻辑自洽，深究起来却充满了悖论和矛盾。你是一个迷人的谜题，在理性和感性之间反复横跳。你的存在本身就证明了，世界并不是非黑即白的。',
        insights: ['充满矛盾的统一体', '神秘感', '常让人捉摸不透'],
        recommendations: ['不要试图理清所有矛盾', '享受你的复杂性', '用艺术表达你的悖论'],
      },
      {
        id: 'r3',
        name: '莫比乌斯环',
        emoji: '♾️',
        minScore: 361,
        maxScore: 540,
        description: '你的灵魂没有正反面之分。你打破了二元对立，看到了万物之间的连接。你拥有无限的延展性，能够从一个极端平滑地过渡到另一个极端。你是循环，是永恒，是无限。',
        insights: ['非线性思维', '极强的包容性', '能在绝望中看到希望'],
        recommendations: ['寻找志同道合的莫比乌斯环', '注意不要陷入死循环', '打破轮回'],
      },
      {
        id: 'r4',
        name: '分形星云',
        emoji: '🌌',
        minScore: 541,
        maxScore: 800,
        description: '你的灵魂没有固定的形态，而是一个不断自我复制、无限细分的混沌系统。你看似无序，实则蕴含着宇宙最深层的规律。你宏大而微观，每一片碎片里都藏着整个宇宙的信息。',
        insights: ['极度抽象', '通灵体质', '要么是天才要么是疯子'],
        recommendations: ['给自己找一个锚点，别飘太远', '将宏大的想法落地', '小心虚无主义的黑洞'],
      },
    ],
  },
];